apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 3000  # 3000
      targetPort: 3000  # 3000
  type: NodePort
