import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})
const jetBrains = JetBrains_Mono({
  variable: "--font-jetBrains-mono",
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "PicToPlate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetBrains.variable} antialiased`}
      >
        <header>
          <div className="w-full bg-amber-500 h-2"></div>
          <nav className="mx-auto max-w-7xl p-6 lg:px-8">
            <h1 className="text-3xl font-bold text-amber-500">Pic<span className="text-gray-900">To</span>Plate</h1>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
